#GET http://localhost:4004/odata/v4/product/printhelloworld(input='Hello')


#GET http://localhost:4004/odata/v4/product/addition(num1=5, num2=4)

#GET http://localhost:4004/rest/product/addition(num1=5, num2=4)


#http://localhost:4004/odata/v4/product/MyFunction(category=2)

http://localhost:4004/rest/product/MyFunction(category=1)
